config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="form">
  <%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.input :url %>
  <%= f.submit "Submit flat", class: "btn btn-primary"%>
<% end %>
</div>

app/views/flats/edit.html.erb
<h1>Edit flat</h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <h1 class="headline"><%= "All flats (#{@flats.count})" %></h1>
  <div class="boxes">
  <% @flats.each do |flat| %>
  <div >
    <div class="box">
      <div class="image" style ="background-image: url('<%= flat.url %>')">
      </div>
      <div class="upper-box">
        <h2 class="small-headline"><%= flat.name %></h2>
        <p class="subheadline"><%= flat.address %></p>
        <div class="price-number">
          <p class="number"><%= flat.price_per_night %></p>
          <p class="number"><%= flat.number_of_guests %></p>
        </div>
      </div>
      <div class="lower-box">
        <div class="links">
          <%= link_to "More info", flat_path(flat), class: "link-blue" %>
          <%= link_to "Edit", edit_flat_path(flat), class: "link-yellow" %>
          <%= link_to "Remove", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class: "link-red" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add new flat</h1>
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<div class="background" style ="background-image: url('<%= @flat.url %>')">
  <div class="container-show">
    <div class="main-boxes">
      <div class="header-box">
        <h1 class="headline-big"><%= @flat.name %></h1>
        <h3 class="subheadline-big"><%= @flat.address %></h2>
      </div>
      <div class="description">
        <h2 class="intro">A bit more about this flat...</h2>
        <p class="description-text"> <%= @flat.description %></p>
      </div>
    </div>
    <div class="side-box">
      <div class="details">
        <h4 class="details-headline">Details</h4>
        <div class="detail-numbers">
          <p class="number-guests"> <%= @flat.number_of_guests %></p>
          <p class="price-night"> <%= @flat.price_per_night %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="nav-bar">
    <p class="nav-name">Simple Airbnb</p>
    <%= link_to "Add new flat", new_flat_path, class: "btn btn-primary" %>
  </div>
    <%= yield %>
  </body>
</html>